personal-website/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  get 'about' => 'home#about'
  get 'resume' => 'home#resume'
  resources 'articles'

  root to: "home#index"
end

personal-website/app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :feeds

  validates_presence_of :name
end

personal-website/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

personal-website/app/models/article.rb
class Article < ApplicationRecord
  include MarkdownConcern
  include PaginationConcern

  page_size 5

  ALLOWED_TAGS = %w(table thead tbody td th tr p ul ol li h1 h2 h3 h4 h5 h6 h7 code em a img)

  convert_markdown :body

  attr_accessor :skip_date_validation

  belongs_to :admin
  belongs_to :feed, optional: true

  scope :published, -> {where(removed_at: nil).where('publish_date < ?', Time.now).order(publish_date: :desc)}

  validates_presence_of :body, :publish_date
  validate :publish_date_in_future, on: :create, if: -> {!skip_date_validation}

  before_validation :set_publish_date
  before_validation :detect_emoji

  def source_name
    unless source.blank?
      source.split('/').select{|s| s.include? '.'}.first
    end
  end

  private

  def publish_date_in_future
    if self.publish_date && self.publish_date < Time.now
      self.errors.add(:publish_date, "must be in future")
    end
  end

  def set_publish_date
    if self.publish_date.blank?
      self.publish_date = 1.minute.from_now
    end
  end

  def detect_emoji
    if self.emoji.blank? && body.blank? == false
      emojis = body.scan(Unicode::Emoji::REGEX)

      if emojis.length > 0
        self.emoji = emojis[0]
      end
    end
  end
end

personal-website/app/models/concerns/markdown_concern.rb
require 'active_support/concern'

# Converts markdown in one column into HTML in another column
# Usage:
#
# class Foo
#   include MarkdownConcern
#   convert_markdown :body, :converted_body, highlight: true
module MarkdownConcern
  extend ActiveSupport::Concern

  DEFAULT_MARKDOWN_OPTIONS = {autolink: true, space_after_headers: true, tables: true, link_attributes: {rel: 'nofollow', target: "_blank"}}

  included do
    class_attribute :markdown_source_column
    class_attribute :markdown_destination_column
    class_attribute :markdown_conversion_options

    before_save :set_converted_markdown

    def reconvert_markdown
      self.set_converted_markdown(true)
      self.save
    end
  end

  class_methods do
    def convert_markdown(source_column, destination_column=nil, options={})
      if destination_column.blank?
        destination_column = "parsed_#{source_column}"
      end

      self.markdown_source_column = source_column
      self.markdown_destination_column = destination_column
      self.markdown_conversion_options = DEFAULT_MARKDOWN_OPTIONS.merge options
    end
  end

  protected

  def set_converted_markdown(force_convert=false)
    if force_convert || self.send("#{self.class.markdown_source_column}_changed?")
      self.send("#{self.class.markdown_destination_column}=", markdown_parser.render(self.send(self.class.markdown_source_column)))
    end
  end

  def markdown_parser
    @markdown_parser ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, self.class.markdown_conversion_options)
  end
end

personal-website/app/models/concerns/pagination_concern.rb
require 'active_support/concern'

module PaginationConcern
  extend ActiveSupport::Concern

  DEFAULT_PAGE_SIZE = 10

  included do
    class_attribute :page_size_value

    page_size DEFAULT_PAGE_SIZE


  end

  class_methods do
    def page_size(page_size)
      self.page_size_value = page_size
    end

    def page(page=1)
      if page.blank? || page < 1
        page = 1
      end
      limit(self.page_size_value).offset((page - 1) * self.page_size_value)
    end

    def total_pages
      (count / self.page_size_value).ceil
    end
  end
end

personal-website/app/models/feed.rb
require 'net/http'
require 'uri'

class Feed < ApplicationRecord
  belongs_to :admin
  has_many :articles

  validates_presence_of :url, :name
  validates_numericality_of :minutes_between_fetches, greater_than_or_equal_to: 5
  validates :url, :presence => true, :url => true

  def retrieve_feed
    if last_fetched_at.nil? || last_fetched_at < minutes_between_fetches.minutes.ago
      feed = Feedjira.parse(Net::HTTP.get_response(URI.parse(url)).body)

      feed.entries.each do |entry|
        article = Article.find_or_initialize_by(source: entry.url, feed: self)

        unless article.persisted?
          article.title = entry.title
          article.parsed_body = entry.summary || entry.content
          article.body = entry.summary || entry.content
          article.publish_date = entry.published
          article.skip_date_validation = true
          article.admin = self.admin
          article.save
        end
      end
      self.last_fetched_at = Time.now
      self.save
    end
  end
end

personal-website/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include OffsetConcern
  include PaginationControllerConcern
end

personal-website/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_article

  def new
    @article = Article.new
    render 'edit'
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.admin = current_admin

    if @article.save
      redirect_to root_path
    else
      puts @article.errors.as_json
      respond_to do |format|
        format.html { render 'edit'}
      end
    end
  end

  def update
    if @article.update(article_params)
      render 'edit'
    else
      render 'edit'
    end
  end

  def destroy
    @article.update(removed_at: Time.now)
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:body, :publish_date, :emoji, :title, :location, :source)
  end

  def set_article
    @article = Article.where(removed_at: nil).find_by_id(params[:id])
  end
end

personal-website/app/controllers/concerns/offset_concern.rb
require 'active_support/concern'

module OffsetConcern
  extend ActiveSupport::Concern

  DEFAULT_LIMIT = 12

  included do
    class_attribute :default_offset_value
    class_attribute :default_limit_value

    default_limit DEFAULT_LIMIT
  end

  class_methods do
    def default_offset(offset)
      self.default_offset_value = offset
    end

    def default_limit(limit)
      self.default_limit_value = limit
    end
  end

  def limit_param
    @limit ||= get_limit
  end

  def offset_param
    @offset ||= get_offset
  end

  private

  def get_offset
    if params[:offset]
      begin
        params[:offset].to_i
      rescue Exception => e
        0
      end
    else
      0
    end
  end

  def get_limit
    if params[:limit]
      begin
        params[:limit].to_i
      rescue Exception => e
        self.class.default_limit_value
      end
    else
      self.class.default_limit_value
    end
  end
end

personal-website/app/controllers/concerns/pagination_controller_concern.rb
require 'active_support/concern'

module PaginationControllerConcern
  extend ActiveSupport::Concern

  included do
    def paginate(scope)
      set_page_variables(scope)
      scope.page(@current_page)
    end

    def total_pages
      (count / self.class.page_size_value).ceil
    end
  end

  private

  def set_page_variables(scope)
    @total_pages = scope.total_pages
    @current_page = get_page

    if @current_page <= 1
      @previous_page = nil
      @first_page = nil
    else
      @previous_page = @current_page - 1

      if @current_page > 2
        @first_page = 1
      else
        @first_page = nil
      end
    end
    if @current_page >= @total_pages
      @next_page = nil
      @last_page = nil
    else
      @next_page = @current_page + 1

      if @current_page < @total_pages - 1
        @last_page = @total_pages
      else
        @last_page = nil
      end
    end
  end

  def get_page
    if params[:page]
      begin
        params[:page].to_i
      rescue Exception => e
        1
      end
    else
      1
    end
  end
end

personal-website/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = paginate Article.published
  end

  def about
  end

  def resume
  end
end

personal-website/app/helpers/application_helper.rb
module ApplicationHelper

end

personal-website/app/helpers/articles_helper.rb
module ArticlesHelper
end

personal-website/app/helpers/home_helper.rb
module HomeHelper
end

personal-website/app/views/articles/_article.html.erb
<div class="card container article">
  <div class="card-content">
    <% if article.title.blank? == false %>
      <div class="title is-2">
        <%= article.emoji %> <span class="is-size-3 article-title"><%= article.title %></span>
      </div>
    <% end %>
    <div class="content">
      <%= sanitize article.parsed_body, tags: Article::ALLOWED_TAGS %>
    </div>
    <div class="article-details has-text-grey">
      <div class="article-detail">
        <span class="icon is-small"><%= fa_icon "clock-o" %></span>
        <span class="article-detail-label" title="<%= article.publish_date %>">
          <%= distance_of_time_in_words_to_now article.publish_date %> ago
        </span>
      </div>
      <% unless article.location.blank? %>
        <div class="article-detail">
          <span class="icon is-small"><%= fa_icon "map-marker" %></span>
          <span class="article-detail-label"  title="<%= article.location %>">
            <%=  article.location %>
          </span>
        </div>
      <% end %>
      <% unless article.source.blank? %>
        <a class="article-detail" href="<%=  article.source %>" title="<%= article.title %>">
          <span class="icon is-small"><%= fa_icon "link" %></span>
          <span class="article-detail-label">
            <%=  article.source_name %>
          </span>
        </a>
      <% end %>
      <% if admin_signed_in? %>
        <%= link_to(edit_article_path(article), class: 'article-detail') do %>
          <span class="icon is-small"><%= fa_icon "edit" %></span>
          <span class="article-detail-label">
            Edit
          </span>
        <% end %>
      <% end %>
    </div>

  </div>
</div>

personal-website/app/views/articles/edit.html.erb
<div class="columns">
  <div class="column is-three-quarters">
    <h2 class="title is-3">New Article</h2>

    <% if @article.errors.any? %>
      <div class="notification is-danger">
        <h3 class="title is-5"><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h3>

        <div class="content">
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <%= form_with model: @article, class: "form", local: true  do |f| %>
      <div class="level">
        <div class="level-item level-left is-narrow">
          <div class="field">
            <%= f.label :emoji, class: 'label' %>
            <%= f.text_field :emoji, class: "input emoji", maxlength: 1 %>
          </div>
        </div>
        <div class="level-item level-left is-narrow spacer">
          &nbsp;
        </div>
        <div class="level-item level-left">
          <div class="field title-field">
            <%= f.label :title, class: 'label' %>
            <%= f.text_field :title, class: "input" %>
          </div>
        </div>
      </div>
      <div class="field">
        <%= f.label :location, class: 'label' %>
        <%= f.text_field :location, class: "input" %>
      </div>
      <div class="field">
        <%= f.label :source, class: 'label' %>
        <%= f.text_field :source, class: "input" %>
      </div>
      <div class="field">
        <%= f.label :body, class: 'label' %>
        <%= f.text_area :body, size: "60x12", class: "textarea" %>
      </div>
      <div class="field">
        <%= f.label :publish_date, class: 'label' %>
        <div class=" field is-grouped level">
          <%= f.datetime_select :publish_date, {}, {class: "select"} %>
        </div>
      </div>
      <div class="level">
        <div class="level-left">
          <%= f.submit @article.persisted? ? "Update" : "Create", class: "button is-link" %>
          &nbsp;
          <%= link_to "Cancel", root_path, class: "button is-link is-light" %>

        </div>
        <div class="level-right">
          <% if @article.persisted? %>
            <%= link_to('Destroy', article_path(@article), {method: :delete, class: "button is-danger", data: { confirm: "Are you sure you want to delete #{@article.title}?" }}) %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

personal-website/app/views/home/about.html.erb
<div>About</div>

personal-website/app/views/home/index.html.erb
<div class="mobile-padding columns">
  <div class="column">
    <% if @current_page == 1  %>
      <div class="notification is-info" href="/about">
        I am a skilled full stack developer with over four years hands-on experience in developing, deploying, maintaining and securing REST API servers,
        Javascript single-page applications, mobile apps, and CI/CD systems. Check out my <%= link_to 'Résumé', :resume %>!<br/>
        Or look at the <a href="https://github.com/erullmann/personal-website">source code</a> for this website.
      </div>
    <% end %>
    <% @articles.each do |article| %>
      <%= render "articles/article", article: article %>
    <% end %>
    <div class="container">
      <%= render "layouts/pagination" %>
    </div>
  </div>
</div>

personal-website/app/views/home/resume.html.erb
<div class="mobile-padding columns">
  <div class="column">
    <div class="box">
      <div class="level">
        <div class="level-item level-left">
          <h1 class="title">
            Ernst Rullmann
          </h1>
        </div>
        <div class="level-item level-right">
          <%= link_to(asset_path('resume.pdf', skip_pipeline: true), target: :_blank) do %>
            <span class="icon"><%= fa_icon "file-pdf-o" %></span> PDF
          <% end %>
        </div>
      </div>
      <p>
        Skilled full-stack developer with over four years hands-on experience in developing, deploying, maintaining and
        securing REST API servers, Javascript single-page applications, mobile apps, and CI/CD systems.
      </p>
      <p>
        <a href="mailto:e.rullmann@gmail.com" target="_blank">
          <span class="icon"><%= fa_icon "envelope-o" %></span> Email
        </a>
        <a href="https://www.linkedin.com/in/ernst-rullmann-84858742/" target="_blank">
          <span class="icon"><%= fa_icon "linkedin" %></span> LinkedIn
        </a>
        <a href="https://github.com/erullmann" target="_blank">
          <span class="icon"><%= fa_icon "github" %></span> Github
        </a>
      </p>
    </div>
    <div class="box">
      <h2 class="title is-3">
        Skills
      </h2>
      <div>
        <div class="content">
          <ul>
            <li>Highly skilled with Ruby on Rails, Angular (Typescript/Javascript) and SQL (Postgres).</li>
            <li>Strong working knowledge of modern security, PIHPA and GDPR requirements.</li>
            <li>Experience with Docker; AWS CodePipeline, EC2 and ECS; C#; HTML/CSS; and Java.</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="box">
      <h2 class="title is-3">
        Experience
      </h2>
      <div>
        <h3 class="title is-5">
          Developer, Tuq — Full Time 2017-Present, 3 Coop Terms in 2015-2017
        </h3>
        <div class="content">
          <ul>
            <li>Creating and maintaining complex and up-to-date REST API servers written using Ruby on Rails, PostgreSQL and Elasticsearch.</li>
            <li>Building re-usable components to simplify testing and speed up future development.</li>
            <li>Developing complex mobile (iOS and Android) and single-page (Angular/Typescript) applications that interact with IoT devices.</li>
            <li>Performing security and code quality assessments on existing code bases and developing short and long-term strategies to mitigate and resolve issues.</li>
            <li>Developing Docker images and CI/CD solutions to build, test and deploy servers.</li>
            <li>Working with clients to plan applications, databases and APIs that meet their needs, and regularly meeting with them to provide updates, identify issues and define deliverables.</li>
          </ul>
        </div>
      </div>
      <br/>
      <div>
        <h3 class="title is-5">
          Junior Developer, Monolith Interactive — 2 Coop Terms in 2014-2015
        </h3>
        <div class="content">
          <ul>
            <li>Built and maintained websites and APIs using Ruby on Rails and PostgreSQL.</li>
            <li>Developed Android mobile apps that interact with REST APIs and play video and audio media.</li>
          </ul>
        </div>
      </div>
      <br/>
      <div>
        <h3 class="title is-5">
          Junior Developer, Workopolis — Coop May - August 2013
        </h3>
        <div class="content">
          <ul>
            <li>Constructed and styled HTML website and email templates according to mock-ups.</li>
            <li>Assessed and restyled automated emails to work correctly with various email clients.</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="box">
      <h2 class="title is-3">
        Education
      </h2>
      <div>
        <h3 class="title is-5">
          University of Waterloo — Honours Bachelors of Computer Science, 2012-2017
        </h3>
        <div class="content">
          <ul>
            <li>Completed Graphics and Real-Time Operating Systems ("Trains") courses.</li>
            <li>Minor in Combinatorics and Optimization.</li>
          </ul>
        </div>
      </div>
    </div>
    <br/>
  </div>
</div>
<br/>

personal-website/app/views/layouts/_favicon.html.erb
<%= favicon_link_tag "apple-touch-icon.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "180x180" %>

<% %w(16 32).each do |s| %>
  <%= favicon_link_tag "favicon-#{s}x#{s}.png", rel: 'icon', type: 'image/png', sizes: "#{s}x#{s}" %>
<% end %>

personal-website/app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">

      <a class="navbar-item" href="/">
        <%= image_tag 'android-chrome-192x192.png' %>
        &nbsp;
        <p class="title">Ernst Rullmann</p>
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <%= link_to "Home", :root, class: 'navbar-item' %>
        <%= link_to "Résumé", :resume, class: 'navbar-item' %>

        <% if admin_signed_in? %>
          <%= link_to "New Post", new_article_path, class: 'navbar-item' %>
        <% end %>
      </div>
      <div class="navbar-end">
        <a href="https://www.linkedin.com/in/ernst-rullmann-84858742/" target="_blank" class="navbar-item">
          <span class="icon"><%= fa_icon "linkedin" %></span>
        </a>
        <a href="https://github.com/erullmann" class="navbar-item" target="_blank">
          <span class="icon"><%= fa_icon "github" %></span>
        </a>
      </div>
    </div>
  </div>
</nav>

personal-website/app/views/layouts/_pagination.html.erb
<nav class="pagination is-centered" role="navigation" aria-label="pagination">
  <ul class="pagination-list">
    <% if @first_page %>
      <li>
        <%= link_to @first_page.to_s, url_for(:page => @first_page), class: "pagination-link" %>
      </li>
      <% if @previous_page - @first_page > 1 %>
        <li><span class="pagination-ellipsis">&hellip;</span></li>
      <% end %>
    <% end %>
    <% if @previous_page %>
      <%= link_to @previous_page.to_s, url_for(:page => @previous_page), class: "pagination-link" %>
    <% end %>
    <%= link_to @current_page.to_s, url_for(:page => @current_page), class: "pagination-link is-current" %>
    <% if @next_page %>
      <%= link_to @next_page.to_s, url_for(:page => @next_page), class: "pagination-link" %>
    <% end %>
    <% if @last_page %>
      <% if @last_page - @next_page > 1 %>
        <li><span class="pagination-ellipsis">&hellip;</span></li>
      <% end %>
      <li>
        <%= link_to @last_page.to_s, url_for(:page => @last_page), class: "pagination-link" %>
      </li>
    <% end %>
  </ul>
</nav>

personal-website/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ernst Rullmann</title>
    <meta name="description" content="I am a skilled full stack developer with over four years hands-on experience in developing, deploying, maintaining and securing REST API servers, Javascript single-page applications, mobile apps, and CI/CD systems.">
    <meta name="keywords" content="Ruby, Rails, Javascript, Angular, Software Developer, Developer">
    <meta name="author" content="Ernst Rullmann">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render "layouts/favicon" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="columns">
    <div class="column is-half container">
      <div class="container">
        <%= render "layouts/navbar" %>

        <% unless notice.blank? %>
          <p class="notification is-success"><%= notice %></p>
        <% end %>
        <% unless alert.blank? %>
          <p class="notification is-warning"><%= alert %></p>
        <% end %>

        <%= yield %>
      </div>

    </div>


  </div>

  <div class="footer columns">
    <div class="container column is-half">
      &#9400; <%= Time.now.strftime('%Y') %> Ernst Rullmann
      <br/>
      <% if admin_signed_in? %>
        <%= link_to('Logout', destroy_admin_session_path, method: :delete, class: "login-link") %>
      <% else %>
        <%= link_to 'Login', new_admin_session_path, class: "login-link" %>
      <% end %>
    </div>
  </div>
  </body>
</html>